"""modefiy user fullname unique constraint

Revision ID: dad6c63857f4
Revises: 47d777e7b8f1
Create Date: 2023-03-08 23:50:56.979196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad6c63857f4'
down_revision = '47d777e7b8f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_full_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_full_name_key', 'user', ['full_name'])
    # ### end Alembic commands ###
